### ISSUE TITLE
All radio buttons on the website must be binded to their label

### ISSUE THREAD

**Issue by HarrisRobin** [HarrisRobin/Things-ToDo#7]
https://thingsdo.herokuapp.com/event/edit/2/calendar

For example in the calendar view, clicking on the calendar image must tick the radio button. You do this by wrapping it in a <label> and giving it the attribute 'for=ID' that is respective to the radio button's id & name.

Let me know if this isn't clear for you.

**Comment by gaudreaujacksoncharles** [comment]
Ok makes sense! Thanks.

**Comment by gaudreaujacksoncharles** [comment]
Done in calendar!
